# Generated by Django 5.2.7 on 2025-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
